=== khalillakhdhar/xml-json/personnes.dtd
<!ELEMENT personnes (personne+)>
<!ELEMENT personne (id,prenom,nom,age*)>
<!ATTLIST personne id ID #REQUIRED>
<!ATTLIST personne nom NMTOKEN #REQUIRED>
<!ATTLIST personne prenom NMTOKEN #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST age value NMTOKEN  #REQUIRED>

=== khalillakhdhar/xml-json/personnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personnes SYSTEM "personnes.dtd">
<!--l'objet (personnes)-->
<personnes>
<!-- l'instance (personne) -->
<personne>
<!-- les attributs de l'instance1 (id=5)...-->
<id>5</id>
<prenom>Jérémy</prenom>
<nom>PERROUAULT</nom>
<age value="6" />
<age>6</age>


</personne>
<!--fin de l'instance 1-->
<!-- début de l'instance 2-->
<personne>

<id>6</id>
<prenom>Allissa</prenom>
<nom>PERROUAULT</nom>
<age>16</age>

</personne>
<!--possible mais je ne recommande pas-->
<!--fin de l'instance 2-->
</personnes>
