=== khalillakhdhar/xml-json/xsd/produits.xsd
<?xml version="1.0" ?>
<category
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="produits.xsd">
<!-- ElÃ©ments -->
</category>
<xsd:element name="category">
<xsd:complexType>
<xsd:sequence>
    <xsd:attribute name="id" type="xsd:int"></xsd:attribute>
    <xsd:attribute name="titre" type="xsd:string"></xsd:attribute>
    
</xsd:sequence>


</xsd:complexType>


</xsd:element>
<xsd:element name="taxe" type="xsd:double"></xsd:element>

=== khalillakhdhar/xml-json/xsd/xmldata.xml
<?xml version="1.0" ?>
<category
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="produits.xsd">
</category>
<produits>
<category>

<!--invalide pour sequence-->
    <titre>agroalimentaire</titre>
    <id>1</id>
</category>
<category>
<!-- valide pour all-->
    
    <id>1</id>
    <titre>Habilles</titre>
</category>




</produits>
